In [2]:
import numpy as np
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
arr1.shape

(2, 4)

In [6]:
np.arange(2,5)

array([2, 3, 4])

In [7]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [8]:
x = np.arange(1,100,5)

In [9]:
x.shape

(20,)

In [10]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [12]:
x = np.arange(1,100,2)

In [13]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
x.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [15]:
y = x.reshape(5,2,5)

In [16]:
y

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]],

       [[21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39]],

       [[41, 43, 45, 47, 49],
        [51, 53, 55, 57, 59]],

       [[61, 63, 65, 67, 69],
        [71, 73, 75, 77, 79]],

       [[81, 83, 85, 87, 89],
        [91, 93, 95, 97, 99]]])

In [17]:
z = np.arange(0,40).reshape(2,2,2,5)

In [18]:
z

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

In [19]:
z.ndim,z.shape

(4, (2, 2, 2, 5))

In [20]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones([4,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [24]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [26]:
np.linspace(1,10,10,retstep = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [27]:
np.linspace(1,10,10,retstep = True,dtype=int)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 1.0)

In [30]:
np.linspace(1,10,10,retstep = True,dtype=int)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 1.0)

In [34]:
#Identity Matrix
np.eye(3, 3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
np.linspace(1,10,20).reshape(4,5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])